name: Build

on: [workflow_dispatch, push]

jobs:
  vite_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./
      - working-directory: ./vite/web
        run: npm i && npm build
      - working-directory: ./vite/nestJs
        run: npm i && npm build
  vite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./
      - working-directory: ./vite/web
        run: pnpm i && pnpm build
      - working-directory: ./vite/nestJs
        run: pnpm i && pnpm build
  webpack_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./
      - working-directory: ./webpack/web
        run: npm i && npm build
      - working-directory: ./webpack/nestJs
        run: npm i && npm build
  webpack:
    runs-on: ubuntu-latest
    steps:
      - uses: ./ctions/checkout@v4
      - name: Setup
        uses: ./
      - working-directory: ./webpack/web
        run: pnpm i && pnpm build
      - working-directory: ./webpack/nestJs
        run: pnpm i && pnpm build
  rspack_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./
      - working-directory: ./rspack/web
        run: npm i && npm build
      - working-directory: ./rspack/nestJs
        run: npm i && npm build
  rspack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./
      - working-directory: ./rspack/web
        run: pnpm i && pnpm build
      - working-directory: ./rspack/nestJs
        run: pnpm i && pnpm build
  farm_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: ./ctions/checkout@v4
      - name: Setup
        uses: ./
      - working-directory: ./farm/web
        run: npm i && npm build
      - working-directory: ./farm/nestJs
        run: npm i && npm build
  farm:
    runs-on: ubuntu-latest
    steps:
      - uses: ./ctions/checkout@v4
      - name: Setup
        uses: ./
      - working-directory: ./farm/web
        run: pnpm i && pnpm build
      - working-directory: ./farm/nestJs
        run: pnpm i && pnpm build